server:
  port: 8761

spring:
  application:
    name: mood
  cloud:
    config:
      url: http://127.0.0.1:8888
      name: config-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false