server:
  port: 0
token:
  expiration_time: 864000000
  secret: mood_user_token
spring:
  application:
    name: matching-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  datasource:
    url: jdbc:mariadb://localhost:3306/mooddb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: '00000000'
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
logging:
  level:
    com.mood.matchingservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics