server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seojeonghyeon/mood-cloud-config.git
          username: seojeonghyeon
          password: '{cipher}7f670856f84e128bf371ea2e48d26658fad70a56a67324a674baeb97f9e2693ad4b371a11e0f5d0c73ca051ae2b4352e9f3ccd5b6da84f3e8fe782cb0ff2cc86'
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

