
server:
  port: 8000
token:
  expiration_time: 864000000
  secret: mood_user_token
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        # login
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #3
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/autologin
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        #regist
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/regist
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #checkEmail
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/checkEmail
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #checkEmail
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/checkNickname
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #sendCertification
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/sendCertification
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #certificateNumber
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/certificateNumber
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #sendRegistCertification
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/sendRegistCertification
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #checkRegistCertification
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/checkRegistCertification
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #findByEmail
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/findByEmail
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #findByPassword
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/findByPassword
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #1
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #2
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #3
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        #4
        - id: lock-service
          uri: lb://LOCK-SERVICE
          predicates:
            - Path=/lock-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/lock-service/(?<segment>.*), /$\{segment}
        #5
        - id: lock-service
          uri: lb://LOCK-SERVICE
          predicates:
            - Path=/lock-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/lock-service/(?<segment>.*), /$\{segment}
        #6
        - id: lock-service
          uri: lb://LOCK-SERVICE
          predicates:
            - Path=/lock-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/lock-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        #POST SERVICE - GET
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
        #POSTSERVICE -POST
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
management:
  endpoints:
    web:
      exposure:
        include: health, beans, httptrace, info, metrics